services:    
  database:
    container_name: db-inventario-aiops
    hostname: db-inventario-aiops
    image: postgres:13.4-alpine
    restart: always
    user: root
    volumes:
      - ./.datastorage:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=fce02f51134186c997de29986f805343
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db-inventario-aiops
      - TZ=America/Sao_Paulo
    ports:
      - 5434:5434
    command: -p 5434

  pgadmin:
    container_name: pgadmin-inventario-aiops
    hostname: pgadmin-inventario-aiops
    image: dpage/pgadmin4
    restart: unless-stopped
    volumes:
       - ./.pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 5050:80
    depends_on:
      - database
      
  backend:
    container_name: backend-inventario-aiops
    hostname: backend-inventario-aiops
    build: ./backend
    restart: always
    volumes:
      - ./backend:/backend
    environment:
      DB_HOST: db-inventario-aiops
      DB_USER: postgres
      DB_PASSWORD: fce02f51134186c997de29986f805343
      DJANGO_SUPERUSER_PASSWORD: admin
    working_dir: /backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000

  frontend:
    container_name: frontend-inventario-aiops
    hostname: frontend-inventario-aiops
    build: ./frontend
    restart: always
    volumes:
      - ./frontend/:/frontend
    working_dir: /frontend
    command: sh entrypoint.sh
    ports:
      - 3031:3000
