# Generated by Django 4.1.2 on 2022-11-25 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('observacao', models.CharField(max_length=255, null=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conta de Serviço',
                'verbose_name_plural': 'Contas de Serviços',
                'db_table': 'inventario_contas_servicos',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('observacao', models.CharField(max_length=255, null=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'inventario_empresas',
            },
        ),
        migrations.CreateModel(
            name='Integracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('observacao', models.CharField(max_length=255, null=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integração',
                'verbose_name_plural': 'Integrações',
                'db_table': 'inventario_integracoes',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('area_negocio', models.CharField(max_length=30, verbose_name='Área de Negócio')),
                ('observacao', models.CharField(max_length=255, null=True, verbose_name='Observação')),
                ('tipo', models.CharField(choices=[('A', 'Ambiente'), ('B', 'Aplicacao'), ('C', 'Automacao'), ('D', 'RPA Uipath')], default='A', max_length=1, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'db_table': 'inventario_projetos',
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('A', 'Servidor Aplicacional'), ('B', 'Banco de Dados')], default='A', max_length=1, verbose_name='Tipo')),
                ('ambiente', models.CharField(choices=[('PRD', 'Produção'), ('DEV', 'Desenvolvimento'), ('HML', 'Homologação'), ('TST', 'Teste')], default='PRD', max_length=3, verbose_name='Ambiente')),
                ('observacao', models.CharField(max_length=255, null=True, verbose_name='Observação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Servidor',
                'verbose_name_plural': 'Servidores',
                'db_table': 'inventario_servidores',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conta_servico', models.ManyToManyField(related_name='conta_servico', to='inventario.contaservico', verbose_name='Conta de Serviço')),
                ('integracao', models.ManyToManyField(related_name='integracao', to='inventario.integracao', verbose_name='Integração')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='inventario.projeto', verbose_name='Projeto')),
                ('servidor', models.ManyToManyField(related_name='servidor', to='inventario.servidor', verbose_name='Servidor')),
            ],
            options={
                'verbose_name': 'Inventário',
                'verbose_name_plural': 'Inventários',
                'db_table': 'inventario_inventarios',
            },
        ),
        migrations.AddField(
            model_name='contaservico',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.empresa', verbose_name='Empresa'),
        ),
    ]
