# Generated by Django 4.1.2 on 2022-10-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaservico',
            name='nome',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='contaservico',
            name='observacao',
            field=models.CharField(max_length=255, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='observacao',
            field=models.CharField(max_length=255, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='integracao',
            name='nome',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='integracao',
            name='observacao',
            field=models.CharField(max_length=255, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='observacao',
            field=models.CharField(max_length=255, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='nome',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='observacao',
            field=models.CharField(max_length=255, null=True, verbose_name='Observação'),
        ),
    ]
