# Generated by Django 4.1.2 on 2022-11-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_inventario_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='conta_servico',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='integracao',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='servidor',
        ),
        migrations.AddField(
            model_name='inventario',
            name='conta_servico',
            field=models.ManyToManyField(related_name='conta_servico', to='inventario.contaservico', verbose_name='Conta de Serviço'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='integracao',
            field=models.ManyToManyField(related_name='integracao', to='inventario.integracao', verbose_name='Integração'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='servidor',
            field=models.ManyToManyField(related_name='servidor', to='inventario.servidor', verbose_name='Servidor'),
        ),
    ]
