# Generated by Django 4.1.2 on 2022-11-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_inventario_conta_servico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='conta_servico',
            field=models.ManyToManyField(related_name='conta_servico', to='inventario.contaservico', verbose_name='Conta de Serviço'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='integracao',
            field=models.ManyToManyField(related_name='integracao', to='inventario.integracao', verbose_name='Integração'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='servidor',
            field=models.ManyToManyField(related_name='servidor', to='inventario.servidor', verbose_name='Servidor'),
        ),
    ]
